### ISSUE TITLE
Error while Saving in test_overlayfunc branch

### ISSUE THREAD

**Issue by shushengfuqin** [atomata/capstone_WebClient#41]
**Describe the bug**
![error](https://user-images.githubusercontent.com/35609373/148116884-bcd6a5d3-6c8c-4d5f-883c-2297aa56ad80.png)

**To Reproduce**
1. On branch test_overlayfunc 
2. Start the server
3. Create new scenario
4. Add actions to actionsequence
5. Click Save
6. The error shall pop up

**Comment by mckenzietsean** [comment]
This error is not exclusive to the test_overlayfunc branch and is caused by how the Azure Database stores the usernames used for logging in. There will need to be proper validation to disable the use of these mentioned "invalid characters", as well as a previously known earlier bug with it also breaking if the username is shorter than 2 characters now.

**Comment by shushengfuqin** [comment]
Okay, so maybe for future reference we can make a sort of validator indicator if we have the time? 
But i'll close this issue for now
